language: go

matrix:
    include:
      - os: linux
        go: 1.12.x
        cache:
          directories:
            - $HOME/.cache/go-build
            - $HOME/gopath/pkg/mod

      - os: osx
        go: 1.12.x
        cache:
          directories:
            - $HOME/Library/Caches/go-build
            - $HOME/gopath/pkg/mod

      - os: linux
        go: 1.13.x
        cache:
          directories:
            - $HOME/.cache/go-build
            - $HOME/gopath/pkg/mod

      - os: osx
        go: 1.13.x
        cache:
          directories:
            - $HOME/Library/Caches/go-build
            - $HOME/gopath/pkg/mod

      - os: linux
        go: tip
        cache:
          directories:
            - $HOME/.cache/go-build
            - $HOME/gopath/pkg/mod

      - os: osx
        go: tip
        cache:
          directories:
            - $HOME/Library/Caches/go-build
            - $HOME/gopath/pkg/mod

git:
  depth: 1

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0

install: true

script:
  - golangci-lint run --enable-all -D funlen,gocognit,gocyclo,godox,lll,scopelint,wsl
  - go test -race -v ./...
